const GOAL_PLACEHOLDERS: Record<string, Record<string, string>> = {
  'first-job': {
    title: 'e.g. Junior Software Engineer',
    company: 'e.g. Tech Startup Name',
    degree: 'e.g. B.S. Computer Science',
    institution: 'e.g. State University',
    projectName: 'e.g. Capstone Project',
    role: 'e.g. Team Lead',
    skill: 'e.g. Python, React',
    summary: 'Recent graduate with a degree in... passionate about building...',
    achievement: 'e.g. Completed a full-stack web application',
    certName: 'e.g. AWS Certified Cloud Practitioner',
    issuer: 'e.g. Amazon Web Services',
    language: 'e.g. Tamil',
    awardTitle: 'e.g. Dean\'s List',
  },
  'internship': {
    title: 'e.g. Intern - Software Developer',
    company: 'e.g. Company Name',
    degree: 'e.g. B.S. Computer Science',
    institution: 'e.g. University Name',
    projectName: 'e.g. Internship Project',
    role: 'e.g. Intern',
    skill: 'e.g. Python, HTML',
    summary: 'Enthusiastic student seeking an internship opportunity in...',
    achievement: 'e.g. Assisted in developing a feature used by...',
    certName: 'e.g. Google IT Support Certificate',
    issuer: 'e.g. Coursera',
    language: 'e.g. Tamil',
    awardTitle: 'e.g. Academic Excellence Award',
  },
  'career-switch': {
    title: 'e.g. Junior Developer (Transitioning)',
    company: 'e.g. Current Company',
    degree: 'e.g. B.A. Previous Field',
    institution: 'e.g. University Name',
    projectName: 'e.g. Portfolio Project',
    role: 'e.g. Career Switcher',
    skill: 'e.g. JavaScript, Project Management',
    summary: 'Professional with experience in... transitioning to a career in...',
    achievement: 'e.g. Transferred skills from previous industry to...',
    certName: 'e.g. Coding Bootcamp Certificate',
    issuer: 'e.g. Bootcamp Name',
    language: 'e.g. Tamil',
    awardTitle: 'e.g. Employee of the Month',
  },
  'experienced': {
    title: 'e.g. Senior Software Engineer',
    company: 'e.g. TechCorp Inc.',
    degree: 'e.g. M.S. Computer Science',
    institution: 'e.g. University Name',
    projectName: 'e.g. Enterprise Platform',
    role: 'e.g. Lead Developer',
    skill: 'e.g. TypeScript, AWS, System Design',
    summary: 'Experienced professional with 5+ years in... proven track record of...',
    achievement: 'e.g. Led a team of 5 engineers to deliver...',
    certName: 'e.g. AWS Solutions Architect',
    issuer: 'e.g. Amazon Web Services',
    language: 'e.g. Tamil',
    awardTitle: 'e.g. Best Performer Award',
  },
  'executive': {
    title: 'e.g. Chief Technology Officer',
    company: 'e.g. Organization Name',
    degree: 'e.g. MBA, Technology Management',
    institution: 'e.g. Business School',
    projectName: 'e.g. Strategic Initiative',
    role: 'e.g. Executive Sponsor',
    skill: 'e.g. Strategic Planning, Board Governance',
    summary: 'Visionary executive with a track record of driving organizational growth...',
    achievement: 'e.g. Drove 40% revenue growth through digital transformation',
    certName: 'e.g. Board Director Certification',
    issuer: 'e.g. Institute Name',
    language: 'e.g. Tamil',
    awardTitle: 'e.g. CEO Excellence Award',
  },
};

const DEFAULT: Record<string, string> = {
  title: 'Enter job title',
  company: 'Enter company name',
  degree: 'Enter degree name',
  institution: 'Enter institution name',
  projectName: 'Enter project name',
  role: 'Enter your role',
  skill: 'Add a skill',
  summary: 'Write a professional summary',
  achievement: 'Describe your key achievements and impact',
  certName: 'Enter certification name',
  issuer: 'Enter issuing organization',
  language: 'e.g. Tamil',
  awardTitle: 'Enter award title',
};

export function ph(goal: string | undefined, field: string): string {
  if (goal && GOAL_PLACEHOLDERS[goal] && GOAL_PLACEHOLDERS[goal][field]) {
    return GOAL_PLACEHOLDERS[goal][field];
  }
  return DEFAULT[field] || '';
}