export const getCompanyLogo = (companyName: string): string => {
  if (!companyName) {
    return '';
  }

  // Trinity special case — use local logo (PRIORITY)
  if (companyName.toLowerCase().includes('trinity')) {
    return '/images/company-logos/trinity-logo.png';
  }

  // Nambikkai special case (PRIORITY)
  if (companyName.toLowerCase().includes('nambikkai')) {
    return '/images/company-logos/nambikkai-logo.png';
  }

  // ZyncJobs special case (PRIORITY)
  if (companyName.toLowerCase().includes('zync')) {
    return '/images/zyncjobs-logo.png';
  }

  // Known domain map — use logo.dev (FALLBACK)
  const domain = getCompanyDomain(companyName);
  if (domain) {
    return `https://img.logo.dev/${domain}?token=pk_cY8JBeWnQR6g5m_ymQhBoQ&size=64`;
  }

  // Return empty string instead of avatar fallback
  return '';
};

const getCompanyDomain = (companyName: string): string => {
  const name = companyName.toLowerCase();
  
  // Common company domain mappings
  const domainMap: { [key: string]: string } = {
    // Global Tech Giants
    'google': 'google.com',
    'microsoft': 'microsoft.com',
    'apple': 'apple.com',
    'amazon': 'amazon.com',
    'facebook': 'facebook.com',
    'meta': 'meta.com',
    'netflix': 'netflix.com',
    'tesla': 'tesla.com',
    'uber': 'uber.com',
    'airbnb': 'airbnb.com',
    'spotify': 'spotify.com',
    'twitter': 'twitter.com',
    'x corp': 'x.com',
    'linkedin': 'linkedin.com',
    'instagram': 'instagram.com',
    'youtube': 'youtube.com',
    'tiktok': 'tiktok.com',
    'snapchat': 'snapchat.com',
    'pinterest': 'pinterest.com',
    'reddit': 'reddit.com',
    'discord': 'discord.com',
    'whatsapp': 'whatsapp.com',
    'telegram': 'telegram.org',
    // Software & SaaS
    'adobe': 'adobe.com',
    'salesforce': 'salesforce.com',
    'oracle': 'oracle.com',
    'sap': 'sap.com',
    'servicenow': 'servicenow.com',
    'workday': 'workday.com',
    'hubspot': 'hubspot.com',
    'zendesk': 'zendesk.com',
    'freshworks': 'freshworks.com',
    'zoho': 'zoho.com',
    'atlassian': 'atlassian.com',
    'jira': 'atlassian.com',
    'confluence': 'atlassian.com',
    'slack': 'slack.com',
    'zoom': 'zoom.us',
    'dropbox': 'dropbox.com',
    'box': 'box.com',
    'notion': 'notion.so',
    'figma': 'figma.com',
    'canva': 'canva.com',
    'asana': 'asana.com',
    'monday': 'monday.com',
    'trello': 'trello.com',
    'airtable': 'airtable.com',
    'clickup': 'clickup.com',
    'miro': 'miro.com',
    'intercom': 'intercom.com',
    'segment': 'segment.com',
    'mixpanel': 'mixpanel.com',
    'amplitude': 'amplitude.com',
    'datadog': 'datadoghq.com',
    'splunk': 'splunk.com',
    'pagerduty': 'pagerduty.com',
    'new relic': 'newrelic.com',
    'grafana': 'grafana.com',
    // Cloud & DevOps
    'aws': 'aws.amazon.com',
    'azure': 'azure.microsoft.com',
    'gcp': 'cloud.google.com',
    'google cloud': 'cloud.google.com',
    'digitalocean': 'digitalocean.com',
    'cloudflare': 'cloudflare.com',
    'fastly': 'fastly.com',
    'vercel': 'vercel.com',
    'netlify': 'netlify.com',
    'heroku': 'heroku.com',
    'docker': 'docker.com',
    'hashicorp': 'hashicorp.com',
    'terraform': 'terraform.io',
    'github': 'github.com',
    'gitlab': 'gitlab.com',
    'bitbucket': 'bitbucket.org',
    'jenkins': 'jenkins.io',
    'circleci': 'circleci.com',
    // Databases & Data
    'mongodb': 'mongodb.com',
    'redis': 'redis.com',
    'elastic': 'elastic.co',
    'elasticsearch': 'elastic.co',
    'snowflake': 'snowflake.com',
    'databricks': 'databricks.com',
    'confluent': 'confluent.io',
    'dbt labs': 'getdbt.com',
    'fivetran': 'fivetran.com',
    'tableau': 'tableau.com',
    'looker': 'looker.com',
    'power bi': 'microsoft.com',
    // Fintech & Payments
    'paypal': 'paypal.com',
    'stripe': 'stripe.com',
    'square': 'squareup.com',
    'razorpay': 'razorpay.com',
    'paytm': 'paytm.com',
    'phonepe': 'phonepe.com',
    'gpay': 'pay.google.com',
    'visa': 'visa.com',
    'mastercard': 'mastercard.com',
    'american express': 'americanexpress.com',
    'amex': 'americanexpress.com',
    'robinhood': 'robinhood.com',
    'coinbase': 'coinbase.com',
    'binance': 'binance.com',
    'zerodha': 'zerodha.com',
    'groww': 'groww.in',
    'cred': 'cred.club',
    'bharat pe': 'bharatpe.com',
    'bharatpe': 'bharatpe.com',
    'mobikwik': 'mobikwik.com',
    // E-commerce & Retail
    'flipkart': 'flipkart.com',
    'meesho': 'meesho.com',
    'myntra': 'myntra.com',
    'nykaa': 'nykaa.com',
    'snapdeal': 'snapdeal.com',
    'ebay': 'ebay.com',
    'shopify': 'shopify.com',
    'woocommerce': 'woocommerce.com',
    'bigcommerce': 'bigcommerce.com',
    'walmart': 'walmart.com',
    'target': 'target.com',
    'ikea': 'ikea.com',
    // Indian IT Giants
    'tcs': 'tcs.com',
    'tata consultancy': 'tcs.com',
    'infosys': 'infosys.com',
    'wipro': 'wipro.com',
    'hcl': 'hcltech.com',
    'hcltech': 'hcltech.com',
    'tech mahindra': 'techmahindra.com',
    'mphasis': 'mphasis.com',
    'hexaware': 'hexaware.com',
    'mindtree': 'mindtree.com',
    'ltimindtree': 'ltimindtree.com',
    'l&t technology': 'ltts.com',
    'ltts': 'ltts.com',
    'persistent': 'persistent.com',
    'persistent systems': 'persistent.com',
    'coforge': 'coforge.com',
    'niit technologies': 'niit.com',
    'kpit': 'kpit.com',
    'cyient': 'cyient.com',
    'zensar': 'zensar.com',
    'mastech': 'mastech.com',
    'sonata software': 'sonata-software.com',
    // Global IT Services
    'accenture': 'accenture.com',
    'ibm': 'ibm.com',
    'capgemini': 'capgemini.com',
    'cognizant': 'cognizant.com',
    'deloitte': 'deloitte.com',
    'pwc': 'pwc.com',
    'kpmg': 'kpmg.com',
    'ey': 'ey.com',
    'ernst & young': 'ey.com',
    'mckinsey': 'mckinsey.com',
    'bcg': 'bcg.com',
    'boston consulting': 'bcg.com',
    'bain': 'bain.com',
    'gartner': 'gartner.com',
    'dxc technology': 'dxc.com',
    'unisys': 'unisys.com',
    'cgi': 'cgi.com',
    'ntt data': 'nttdata.com',
    'fujitsu': 'fujitsu.com',
    'atos': 'atos.net',
    'sopra steria': 'soprasteria.com',
    // Semiconductors & Hardware
    'intel': 'intel.com',
    'nvidia': 'nvidia.com',
    'amd': 'amd.com',
    'qualcomm': 'qualcomm.com',
    'arm': 'arm.com',
    'broadcom': 'broadcom.com',
    'texas instruments': 'ti.com',
    'samsung': 'samsung.com',
    'lg': 'lg.com',
    'sony': 'sony.com',
    'panasonic': 'panasonic.com',
    'dell': 'dell.com',
    'hp': 'hp.com',
    'lenovo': 'lenovo.com',
    'asus': 'asus.com',
    'acer': 'acer.com',
    // Telecom
    'jio': 'jio.com',
    'reliance jio': 'jio.com',
    'airtel': 'airtel.in',
    'vodafone': 'vodafone.com',
    'bsnl': 'bsnl.co.in',
    'vi': 'myvi.in',
    'at&t': 'att.com',
    'verizon': 'verizon.com',
    't-mobile': 't-mobile.com',
    // Startups & Unicorns (India)
    'byju': 'byjus.com',
    'byjus': 'byjus.com',
    'ola': 'olacabs.com',
    'swiggy': 'swiggy.com',
    'zomato': 'zomato.com',
    'dunzo': 'dunzo.com',
    'blinkit': 'blinkit.com',
    'zepto': 'zeptonow.com',
    'instamart': 'swiggy.com',
    'oyo': 'oyorooms.com',
    'makeMyTrip': 'makemytrip.com',
    'makemytrip': 'makemytrip.com',
    'cleartrip': 'cleartrip.com',
    'ixigo': 'ixigo.com',
    'urban company': 'urbancompany.com',
    'urbanclap': 'urbancompany.com',
    'lenskart': 'lenskart.com',
    'boat': 'boat-lifestyle.com',
    'noise': 'gonoise.com',
    'dream11': 'dream11.com',
    'mpl': 'mpl.live',
    'unacademy': 'unacademy.com',
    'vedantu': 'vedantu.com',
    'upgrad': 'upgrad.com',
    'simplilearn': 'simplilearn.com',
    'great learning': 'greatlearning.in',
    'chargebee': 'chargebee.com',
    'postman': 'postman.com',
    'browserstack': 'browserstack.com',
    'hasura': 'hasura.io',
    'setu': 'setu.co',
    'open financial': 'open.money',
    'khatabook': 'khatabook.com',
    'ofbusiness': 'ofbusiness.com',
    'moglix': 'moglix.com',
    'udaan': 'udaan.com',
    'delhivery': 'delhivery.com',
    'shiprocket': 'shiprocket.in',
    'ecom express': 'ecomexpress.in',
    'shadowfax': 'shadowfax.in',
    'porter': 'porter.in',
    'rapido': 'rapido.bike',
    'bounce': 'bounce.bike',
    'yulu': 'yulu.bike',
    // Global Unicorns & Startups
    'openai': 'openai.com',
    'anthropic': 'anthropic.com',
    'mistral': 'mistral.ai',
    'hugging face': 'huggingface.co',
    'cohere': 'cohere.com',
    'stability ai': 'stability.ai',
    'midjourney': 'midjourney.com',
    'palantir': 'palantir.com',
    'anduril': 'anduril.com',
    'scale ai': 'scale.com',
    'coatue': 'coatue.com',
    'plaid': 'plaid.com',
    'chime': 'chime.com',
    'brex': 'brex.com',
    'rippling': 'rippling.com',
    'gusto': 'gusto.com',
    'lattice': 'lattice.com',
    'culture amp': 'cultureamp.com',
    'greenhouse': 'greenhouse.io',
    'lever': 'lever.co',
    'workable': 'workable.com',
    'bamboohr': 'bamboohr.com',
    'deel': 'deel.com',
    'remote': 'remote.com',
    'oyster': 'oysterhr.com',
    'twilio': 'twilio.com',
    'sendgrid': 'sendgrid.com',
    'mailchimp': 'mailchimp.com',
    'klaviyo': 'klaviyo.com',
    'braze': 'braze.com',
    'contentful': 'contentful.com',
    'sanity': 'sanity.io',
    'storyblok': 'storyblok.com',
    'webflow': 'webflow.com',
    'wix': 'wix.com',
    'squarespace': 'squarespace.com',
    'wordpress': 'wordpress.com',
    'godaddy': 'godaddy.com',
    'namecheap': 'namecheap.com',
    // Automotive
    'tata motors': 'tatamotors.com',
    'mahindra': 'mahindra.com',
    'maruti': 'marutisuzuki.com',
    'maruti suzuki': 'marutisuzuki.com',
    'hyundai': 'hyundai.com',
    'kia': 'kia.com',
    'toyota': 'toyota.com',
    'honda': 'honda.com',
    'ford': 'ford.com',
    'bmw': 'bmw.com',
    'mercedes': 'mercedes-benz.com',
    'volkswagen': 'volkswagen.com',
    'ather': 'atherenergy.com',
    'ola electric': 'olaelectric.com',
    'rivian': 'rivian.com',
    'lucid': 'lucidmotors.com',
    // Healthcare & Pharma
    'apollo': 'apollohospitals.com',
    'apollo hospitals': 'apollohospitals.com',
    'fortis': 'fortishealthcare.com',
    'manipal': 'manipalhospitals.com',
    'max healthcare': 'maxhealthcare.in',
    'narayana health': 'narayanahealth.org',
    'sun pharma': 'sunpharma.com',
    'cipla': 'cipla.com',
    'dr reddy': 'drreddys.com',
    'lupin': 'lupin.com',
    'biocon': 'biocon.com',
    'pfizer': 'pfizer.com',
    'johnson & johnson': 'jnj.com',
    'novartis': 'novartis.com',
    'roche': 'roche.com',
    'abbott': 'abbott.com',
    'medtronic': 'medtronic.com',
    'practo': 'practo.com',
    'healthifyme': 'healthifyme.com',
    '1mg': '1mg.com',
    'pharmeasy': 'pharmeasy.in',
    'netmeds': 'netmeds.com',
    // Banking & Finance
    'hdfc': 'hdfcbank.com',
    'hdfc bank': 'hdfcbank.com',
    'icici': 'icicibank.com',
    'icici bank': 'icicibank.com',
    'sbi': 'sbi.co.in',
    'state bank': 'sbi.co.in',
    'axis bank': 'axisbank.com',
    'kotak': 'kotak.com',
    'kotak mahindra': 'kotak.com',
    'yes bank': 'yesbank.in',
    'indusind': 'indusind.com',
    'bajaj finserv': 'bajajfinserv.in',
    'bajaj finance': 'bajajfinserv.in',
    'jpmorgan': 'jpmorgan.com',
    'goldman sachs': 'goldmansachs.com',
    'morgan stanley': 'morganstanley.com',
    'citibank': 'citi.com',
    'barclays': 'barclays.com',
    'hsbc': 'hsbc.com',
    'deutsche bank': 'db.com',
    'ubs': 'ubs.com',
    'blackrock': 'blackrock.com',
    'fidelity': 'fidelity.com',
    'vanguard': 'vanguard.com',
    // Media & Entertainment
    'disney': 'disney.com',
    'warner bros': 'warnerbros.com',
    'sony pictures': 'sonypictures.com',
    'universal': 'universalpictures.com',
    'paramount': 'paramount.com',
    'hbo': 'hbo.com',
    'hulu': 'hulu.com',
    'prime video': 'primevideo.com',
    'hotstar': 'hotstar.com',
    'zee': 'zee5.com',
    'sun tv': 'suntv.com',
    'times of india': 'timesofindia.com',
    'ndtv': 'ndtv.com',
    'india today': 'indiatoday.in',
    'the hindu': 'thehindu.com',
    'hindustan times': 'hindustantimes.com',
    // Logistics & Supply Chain
    'fedex': 'fedex.com',
    'ups': 'ups.com',
    'dhl': 'dhl.com',
    'blue dart': 'bluedart.com',
    'dtdc': 'dtdc.com',
    'xpressbees': 'xpressbees.com',
    'ekart': 'ekartlogistics.com',
    // Conglomerates
    'tata': 'tata.com',
    'tata group': 'tata.com',
    'reliance': 'ril.com',
    'reliance industries': 'ril.com',
    'adani': 'adani.com',
    'adani group': 'adani.com',
    'birla': 'adityabirlacapital.com',
    'aditya birla': 'adityabirlacapital.com',
    'godrej': 'godrej.com',
    'bajaj': 'bajaj.com',
    'larsen & toubro': 'larsentoubro.com',
    'l&t': 'larsentoubro.com',
    'infra': 'larsentoubro.com',
    // Local
    'growthpulss private solutions': 'growthpulss.com',
    'growthpulse solutions': 'growthpulss.com',
    'growthpulse': 'growthpulss.com',
    'growth pulse': 'growthpulss.com',
  };
  
  // Check for exact matches first
  if (domainMap[name]) {
    return domainMap[name];
  }
  
  // Check for partial matches
  for (const [key, domain] of Object.entries(domainMap)) {
    if (name.includes(key) || key.includes(name)) {
      return domain;
    }
  }
  
  // Try to construct domain from company name (only for known patterns)
  return '';
};

export const getSafeCompanyLogo = (job: any): string => {
  const companyName = job.company || job.companyName || job.name || '';
  return getCompanyLogo(companyName);
};

export const getLetterAvatar = (name: string): string => {
  const initials = name.split(' ').map(n => n[0]).join('').toUpperCase();
  return `data:image/svg+xml,${encodeURIComponent(`
    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 40 40">
      <rect width="40" height="40" fill="#3B82F6" rx="8"/>
      <text x="20" y="26" text-anchor="middle" fill="white" font-family="Arial" font-size="16" font-weight="bold">${initials}</text>
    </svg>
  `)}`;
};
